USE [master]
GO
/****** Object:  Database [ToDoAppDb]    Script Date: 27.10.2023 20:37:32 ******/
CREATE DATABASE [ToDoAppDb]
 CONTAINMENT = NONE
GO
ALTER DATABASE [ToDoAppDb] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ToDoAppDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ToDoAppDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ToDoAppDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ToDoAppDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ToDoAppDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ToDoAppDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [ToDoAppDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ToDoAppDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ToDoAppDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ToDoAppDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ToDoAppDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ToDoAppDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ToDoAppDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ToDoAppDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ToDoAppDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ToDoAppDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ToDoAppDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ToDoAppDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ToDoAppDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ToDoAppDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ToDoAppDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ToDoAppDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ToDoAppDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ToDoAppDb] SET RECOVERY FULL 
GO
ALTER DATABASE [ToDoAppDb] SET  MULTI_USER 
GO
ALTER DATABASE [ToDoAppDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ToDoAppDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ToDoAppDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ToDoAppDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ToDoAppDb', N'ON'
GO
USE [ToDoAppDb]
GO
/****** Object:  Table [dbo].[ToDo]    Script Date: 27.10.2023 20:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToDo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Tasks] [nchar](50) NOT NULL,
	[IsTaskCompleted] [bit] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUserId] [int] NOT NULL,
 CONSTRAINT [PK_ToDo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 27.10.2023 20:37:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[ToDoListId] [int] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUserId] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ToDo] ON 

SET IDENTITY_INSERT [dbo].[ToDo] OFF
GO
SET IDENTITY_INSERT [dbo].[User] ON 


INSERT [dbo].[User] ([Id], [Username], [Password], [ToDoListId], [CreateDate], [CreateUserId]) VALUES (1015, N'test@testt', N'test', NULL, CAST(N'2023-10-27T10:06:45.553' AS DateTime), 0)
INSERT [dbo].[User] ([Id], [Username], [Password], [ToDoListId], [CreateDate], [CreateUserId]) VALUES (1016, N'tee@tee', N'tee', NULL, CAST(N'2023-10-27T18:39:15.497' AS DateTime), 0)
SET IDENTITY_INSERT [dbo].[User] OFF
GO
ALTER TABLE [dbo].[ToDo]  WITH CHECK ADD  CONSTRAINT [FK_ToDo_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[ToDo] CHECK CONSTRAINT [FK_ToDo_User]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_ToDo] FOREIGN KEY([ToDoListId])
REFERENCES [dbo].[ToDo] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_ToDo]
GO
USE [master]
GO
ALTER DATABASE [ToDoAppDb] SET READ_WRITE
GO